### ISSUE TITLE
Vadim's feedback

### ISSUE THREAD

**Issue by vmarkovtsev** [FragileTech/ml-ops-quickstart#33]
### 1

```
vadim@vadim-XPS-13-9380:~/Projects$ mloq setup
Usage: mloq setup [OPTIONS] OUTPUT
Try 'mloq setup --help' for help.

Error: Missing argument 'OUTPUT'.
vadim@vadim-XPS-13-9380:~/Projects$ mloq quickstart
Usage: mloq quickstart [OPTIONS] OUTPUT
Try 'mloq quickstart --help' for help.

Error: Missing argument 'OUTPUT'.
```

What's `OUTPUT`? Name it `OUTPUT_DIRECTORY`.

### 2

```
defining template <mloq.configuration.core.ConfigGroup object at 0x7fcaddb29190>
```

### 3

It does not check if the directory is empty and does not ask what to do: overwrite or not overwrite.

### 4

`https://github.com/athenianco/names-matcher.git` -> remove the `.git` suffix

### 5

`Bot account to push from ci` -> `Bot's GitHub login to push commits in CI`

### 6

`['data-science', 'data-viz', 'pytorch']` - you should add "empty"

### 7

I had `requirements.txt` and `setup.py` before running `mloq`.
I answered all the interactive questions and got `file setup.py not written: override False |cond: True`. Both `requirements.txt` and `setup.py` were not overwritten.

### 8

Offer to delete `mloq.yml`.

### 9

Ask whether to generate `pyproject.toml` or not.

### 10

I see a file `MLproject` with some yaml inside. What's this? If it is a feature, ask to generate it.

### 11

Generate `WHAT_MLOQ_GENERATED.md` with the description of each feature the tool generated.

### 12

`Dockerfile` - ask for the name of the base image. Not everybody wants to root in a `fragiletech` image. Offer to embed `fragiletech` image contents directly inside `Dockerfile` so that there are no dependencies.

The default should be `fragiletech` without embeds, that's the right choice :+1:

### 13

`Dockerfile`: in my case, I bootstrap a library and a command line application, so the contents

### 14

`DCO.md` and `LICENSE`. You should ask whether the project is proprietary or not, and if is open source, ask for the license (it is fine to hardcode some well-known licenses list). If it is proprietary, do not generate those files.

### 15

You should update `How to Contribute` in `CONTRIBUTING.md` - the info is outdated.

### 16

`code_of_conduct.md` should be `CODE_OF_CONDUCT.md`

### 17

Offer to run `git init`, `git remote add ssh://git@github.com/chosen user/chosen project`, `git commit -a -m "Generate boilerplate with fragiletech/ml-ops-quickstart"`.

### 18

I chose name `names-matcher`. It generated an invalid Python package directory `names-matcher`, it should be `names_matcher`. You should also validate the name against Python identifier syntax, e.g. no exclamation marks or other weird symbols.

Also, `from names-matcher.__main__ import main`

**Comment by Guillemdb** [comment]
- [ ] 1 Fix/ Remove old commands (not `quickstart`)
- [ ] 2 Clean CLI output
- [ ] 3 Make more clear use of override in `quickstart`
- [x] 4 Remove git suffix
- [x] 5 Update bot description
- [ ] 6 `['data-science', 'data-viz', 'pytorch']` - you should add "empty"
- [ ] 8 Offer to delete `mloq.yml`.
- [ ] 9 Ask whether to generate `pyproject.toml` or not.
- [ ] 10 I see a file `MLproject` with some yaml inside. What's this? If it is a feature, ask to generate it.
- [ ] 11 Generate `WHAT_MLOQ_GENERATED.md` with the description of each feature the tool generated.
- [ ] 12 `Dockerfile` - ask for the name of the base image. Not everybody wants to root in a `fragiletech` image. Offer to embed `fragiletech` image contents directly inside `Dockerfile` so that there are no dependencies. The default should be `fragiletech` without embeds, that's the right choice :+1:
- [ ]  13 Make docker container optional
- [ ] 14 Update to work with proprietary projects.
- [x] 15 `CONTRIBUTING.md`
- [ ] 16 `code_of_conduct.md` should be `CODE_OF_CONDUCT.md`
- [ ] 17 Offer to run `git init`
- [x] 18 Replace `-` with `_` in package files and name

**Comment by Guillemdb** [comment]
Priorities of the day:
- [ ] 16 `code_of_conduct.md` should be `CODE_OF_CONDUCT.md`
- [ ] 20 Simplify configuration parsing
- [ ] 1 Fix/ Remove old commands (not `quickstart`)
- [ ] 6 `['data-science', 'data-viz', 'pytorch']` - you should add "empty"
- [ ] 12 `Dockerfile` - ask for the name of the base image. Not everybody wants to root in a `fragiletech` image. Offer to embed `fragiletech` image contents directly inside `Dockerfile` so that there are no dependencies. The default should be `fragiletech` without embeds, that's the right choice :+1:
- [ ] 14 Update to work with proprietary projects.
- [ ] 19 Add different types of Open Source Licnses.

**Comment by Guillemdb** [comment]
@vmarkovtsev Regarding **12.b**, implementing that is kind of a nightmare. The image contents are generated programmatically in [fragiletech/dockerfiles](https://github.com/FragileTech/dockerfiles), and the image type is chosen based on the highest python version supported, and the need to use CUDA (inferred from the requirements). 

Those FragileTech images only contain a basic python installation and the system dependencies needed to build the most common data science packages. 

If you can think of an straightforward fix please tell me and I'll try to implement it.

**Comment by Guillemdb** [comment]
I already implemented everything that was straightforward. I'm gonna open Issues to address what is currently missing:
- [ ] 9 Ask whether to generate `pyproject.toml` or not.
- [ ] 11 Generate `WHAT_MLOQ_GENERATED.md` with the description of each feature the tool generated.
- [ ] 12.b Offer to embed `fragiletech` image contents directly inside `Dockerfile` so that there are no dependencies. The default should be `fragiletech` without embeds, that's the right choice :+1:
- [ ] 13 Make docker container optional
- [ ] 17 Offer to run `git init`
- [ ] 19 Add different types of Open Source Licenses.
