### ISSUE TITLE
We don't mention pre-commit anywhere

### ISSUE THREAD

**Issue by vmarkovtsev** [FragileTech/ml-ops-quickstart#92]
I see that we define pre-commit hooks but don't mention https://pre-commit.com/ anywhere in the project.

**Comment by Guillemdb** [comment]
Yep, I forgot about them because I don't have pre-commit installed. I haven't touched that file for a long time, so I am not sure if the black hook works as expected. Maybe we should change it for a `make check` run.

Having nice pre-commit hooks can be very helpful to our new apprentices so I'm glad you opened https://github.com/FragileTech/ml-ops-quickstart/pull/94/.
